#!/usr/bin/env php
<?php
require __DIR__ . '/public/app.php';

use App\Console\Kernel;

// kernel
$kernel = new Kernel();

// Parse CLI args
$argv = $_SERVER['argv'] ?? [];
$command = $argv[1] ?? 'list';

// Run schedule
if ($command === 'schedule:run') {
    $kernel->runSchedule();
} else {
    $kernel->runCommand($argv);
}
